config/routes.rb
Rails.application.routes.draw do
  resources :toys
  root "toys#main"

  get 'contakt', to: 'toys#contakt'
  get 'razr', to: 'toys#razr'
  get 'shumelki', to: 'toys#shumelki'
  get 'pyramid', to: 'toys#pyramid'
  get 'lacing', to: 'toys#lacing'
  get 'puzzlespictures', to: 'toys#puzzlespictures'
  get 'looseleaves', to: 'toys#looseleaves'
  get 'sorters', to: 'toys#sorters'
  get 'cubes', to: 'toys#cubes'
  get 'boardgames', to: 'toys#boardgames'
  get 'constructors', to: 'toys#constructors'
  get 'creatorskit', to: 'toys#creatorskit'
  get 'puzzles', to: 'toys#puzzles'
  get 'learningtoread', to: 'toys#learningtoread'
  get 'westudythealphabet', to: 'toys#westudythealphabet'
  get 'languageandcommunication', to: 'toys#languageandcommunication'
  get 'accounteducation', to: 'toys#accounteducation'
  get 'developmentoflogicalthinking', to: 'toys#developmentoflogicalthinking'
  get 'developmentofmemoryandattention', to: 'toys#developmentofmemoryandattention'
  get 'colorsandshapes', to: 'toys#colorsandshapes'
  get 'theworld', to: 'toys#theworld'
  get 'puzzlegames', to: 'toys#puzzlegames'
  get 'teaching', to: 'toys#teaching'
  get 'developing', to: 'toys#developing'
  get 'merry', to: 'toys#merry'
  get 'forthecompany', to: 'toys#forthecompany'
  get 'constructor', to: 'toys#constructor'
  get 'massformodeling', to: 'toys#massformodeling'
  get 'sandformodeling', to: 'toys#sandformodeling'
  get 'puzzle', to: 'toys#puzzle'
  get 'creation', to: 'toys#creation'
  get 'printedproducts', to: 'toys#printedproducts'
  get 'plaything', to: 'toys#plaything'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: [:show, :edit, :update, :destroy]

  # GET /toys
  # GET /toys.json
  def index
    @toys = Toy.all
  end

  def shumelki
    @toys = Toy.where(Podrazdel: "beanbag")
  end

  def pyramid
    @toys = Toy.where(Podrazdel: "pyramid")
  end

  def lacing
    @toys = Toy.where(Podrazdel: "lacing")
  end

  def puzzlespictures
    @toys = Toy.where(Podrazdel: "puzzlespictures")
  end

  def looseleaves
    @toys = Toy.where(Podrazdel: "looseleaves")
  end

  def sorters
    @toys = Toy.where(Podrazdel: "sorters")
  end

  def cubes
    @toys = Toy.where(Podrazdel: "cubes")
  end

  def boardgames
    @toys = Toy.where(Podrazdel: "boardgames")
  end

  def constructors
    @toys = Toy.where(Podrazdel: "constructors")
  end

  def creatorskit
    @toys = Toy.where(Podrazdel: "creatorskit")
  end

  def puzzles
    @toys = Toy.where(Podrazdel: "puzzles")
  end

  def learningtoread
    @toys = Toy.where(Podrazdel: "learningtoread")
  end

  def westudythealphabet
    @toys = Toy.where(Podrazdel: "westudythealphabet")
  end

  def languageandcommunication
    @toys = Toy.where(Podrazdel: "languageandcommunication")
  end

  def accounteducation
    @toys = Toy.where(Podrazdel: "accounteducation")
  end

  def developmentoflogicalthinking
    @toys = Toy.where(Podrazdel: "developmentoflogicalthinking")
  end

  def developmentofmemoryandattention
    @toys = Toy.where(Podrazdel: "developmentofmemoryandattention")
  end

  def colorsandshapes
    @toys = Toy.where(Podrazdel: "colorsandshapes")
  end

  def theworld
    @toys = Toy.where(Podrazdel: "theworld")
  end

  def puzzlegames
    @toys = Toy.where(Podrazdel: "puzzlegames")
  end

  def teaching
    @toys = Toy.where(Podrazdel: "teaching")
  end

  def developing
    @toys = Toy.where(Podrazdel: "developing")
  end

  def merry
    @toys = Toy.where(Podrazdel: "merry")
  end

  def forthecompany
    @toys = Toy.where(Podrazdel: "forthecompany")
  end

  def constructor
    @toys = Toy.where(Podrazdel: "constructor")
  end

  def massformodeling
    @toys = Toy.where(Podrazdel: "massformodeling")
  end

  def sandformodeling
    @toys = Toy.where(Podrazdel: "sandformodeling")
  end

  def puzzle
    @toys = Toy.where(Podrazdel: "puzzle")
  end

  def creation
    @toys = Toy.where(Podrazdel: "creation")
  end

  def printedproducts
    @toys = Toy.where(Podrazdel: "printedproducts")
  end

  def plaything
    @toys = Toy.where(Podrazdel: "plaything")
  end


  # GET /toys/1
  # GET /toys/1.json
  def show
  end

  # GET /toys/new
  def new
    @toy = Toy.new
  end

  # GET /toys/1/edit
  def edit
  end

  # POST /toys
  # POST /toys.json
  def create
    @toy = Toy.new(toy_params)

    respond_to do |format|
      if @toy.save
        format.html { redirect_to @toy, notice: 'Toy was successfully created.' }
        format.json { render :show, status: :created, location: @toy }
      else
        format.html { render :new }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toys/1
  # PATCH/PUT /toys/1.json
  def update
    respond_to do |format|
      if @toy.update(toy_params)
        format.html { redirect_to @toy, notice: 'Toy was successfully updated.' }
        format.json { render :show, status: :ok, location: @toy }
      else
        format.html { render :edit }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1
  # DELETE /toys/1.json
  def destroy
    @toy.destroy
    respond_to do |format|
      format.html { redirect_to toys_url, notice: 'Toy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toy
      @toy = Toy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toy_params
      params.require(:toy).permit(:name, :cost, :info, :image, :Razdel, :Podrazdel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poznavalkin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://allfont.ru/allfont.css?fonts=tatianactt" rel="stylesheet" type="text/css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toys/constructors.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand и toggle сгруппированы для лучшего отображения на мобильных дисплеях -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="/razrbs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-top: 15px"><%= image_tag("/brand.jpeg") %></a>
    </div>
    <div class="container-fluid">
      <%= image_tag("/nadpis.jpeg", class: "navbar-text") %>
      <a href="/contakt" class="navbar-text" style="margin-top: 60px">Наши контакты</a>
      <%#= image_tag("/kalash1.jpg", size: "150x75")%>
    </div>
    <div class="container-fluid">
      <%= image_tag("/kalash1.jpg", size: "170x100") %>
      <%= image_tag("/kalash3.jpg", size: "170x100") %>
      <%= image_tag("/kalash4.jpg", size: "170x100") %>
      <%= image_tag("/kalash5.jpg", size: "170x100") %>
      <%= image_tag("/kalash2.jpg", size: "170x100")%>
    </div>
    <!-- Соберите навигационные ссылки, формы, и другой контент для переключения -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="/razr">Каталог <span class="sr-only">(current)</span></a></li>-->
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Деревянные игрушки <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/shumelki">Шумелки</a></li>
            <li><a href="/pyramid">Пирамидки</a></li>
            <li><a href="/lacing">Шнуровки</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/puzzlespictures">Пазлы-картинки</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/looseleaves">Вкладыши</a></li>
            <li><a href="/sorters">Сортеры</a></li>
            <li><a href="/cubes">Кубики</a></li>
            <li><a href="/boardgames">Настольные игры</a></li>
            <li><a href="/constructors">Конструкторы</a></li>
            <li><a href="/creatorskit">Наборы для творчества</a></li>
            <li><a href="/puzzles">Пазлы</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Обучающие игры <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/learningtoread">Обучение чтению</a></li>
            <li><a href="/westudythealphabet">Изучаем алфавит</a></li>
            <li><a href="/languageandcommunication">Язык и коммуникация</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/accounteducation">Обучение счету</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/developmentoflogicalthinking">Развитие логического мышления</a></li>
            <li><a href="/developmentofmemoryandattention">Развитие памяти и внимания</a></li>
            <li><a href="/colorsandshapes">Цвета и формы</a></li>
            <li><a href="/theworld">Окружающий мир</a></li>
          </ul>
        </li>
        <li><a href="/puzzlegames">Головоломки</a></li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Настольные игры <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/teaching">Обучающие</a></li>
            <li><a href="/developing">Развивающие</a></li>
            <li><a href="/merry">Веселые</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/forthecompany">Для компании</a></li>
          </ul>
        </li>
        <li><a href="/constructor">Конструкторы</a></li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Остальное <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/massformodeling">Масса для лепки</a></li>
            <li><a href="/sandformodeling">Песок для лепки</a></li>
            <li><a href="/puzzle">Пазлы</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/creation">Творчество</a></li>
            <li><a href="/printedproducts">Печатная продукция</a></li>
            <li><a href="/plaything">Игрушки</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<table class="table table-bordered">

  <tbody>
  <% @toys.each do |toy| %>
    <tr style="display: block; Margin-bottom:30px">
      <td style="width: 200px;"><%= toy.name %> &nbsp</td>
      <td><%= toy.cost %> руб. &nbsp</td>
      <td><%= image_tag(toy.image, size: "100x100", alt: toy.image[1..-5]) %> &nbsp</td>
      <td><%= link_to 'Полная информация', toy, class: "btn btn-default" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Toy', new_toy_path %>

app/views/toys/cubes.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand и toggle сгруппированы для лучшего отображения на мобильных дисплеях -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="/razrbs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-top: 15px"><%= image_tag("/brand.jpeg") %></a>
    </div>
    <div class="container-fluid">
      <%= image_tag("/nadpis.jpeg", class: "navbar-text") %>
      <a href="/contakt" class="navbar-text" style="margin-top: 60px">Наши контакты</a>
      <%#= image_tag("/kalash1.jpg", size: "150x75")%>
    </div>
    <div class="container-fluid">
      <%= image_tag("/kalash1.jpg", size: "170x100") %>
      <%= image_tag("/kalash3.jpg", size: "170x100") %>
      <%= image_tag("/kalash4.jpg", size: "170x100") %>
      <%= image_tag("/kalash5.jpg", size: "170x100") %>
      <%= image_tag("/kalash2.jpg", size: "170x100")%>
    </div>
    <!-- Соберите навигационные ссылки, формы, и другой контент для переключения -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="/razr">Каталог <span class="sr-only">(current)</span></a></li>-->
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Деревянные игрушки <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/shumelki">Шумелки</a></li>
            <li><a href="/pyramid">Пирамидки</a></li>
            <li><a href="/lacing">Шнуровки</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/puzzlespictures">Пазлы-картинки</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/looseleaves">Вкладыши</a></li>
            <li><a href="/sorters">Сортеры</a></li>
            <li><a href="/cubes">Кубики</a></li>
            <li><a href="/boardgames">Настольные игры</a></li>
            <li><a href="/constructors">Конструкторы</a></li>
            <li><a href="/creatorskit">Наборы для творчества</a></li>
            <li><a href="/puzzles">Пазлы</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Обучающие игры <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/learningtoread">Обучение чтению</a></li>
            <li><a href="/westudythealphabet">Изучаем алфавит</a></li>
            <li><a href="/languageandcommunication">Язык и коммуникация</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/accounteducation">Обучение счету</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/developmentoflogicalthinking">Развитие логического мышления</a></li>
            <li><a href="/developmentofmemoryandattention">Развитие памяти и внимания</a></li>
            <li><a href="/colorsandshapes">Цвета и формы</a></li>
            <li><a href="/theworld">Окружающий мир</a></li>
          </ul>
        </li>
        <li><a href="/puzzlegames">Головоломки</a></li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Настольные игры <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/teaching">Обучающие</a></li>
            <li><a href="/developing">Развивающие</a></li>
            <li><a href="/merry">Веселые</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/forthecompany">Для компании</a></li>
          </ul>
        </li>
        <li><a href="/constructor">Конструкторы</a></li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Остальное <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/massformodeling">Масса для лепки</a></li>
            <li><a href="/sandformodeling">Песок для лепки</a></li>
            <li><a href="/puzzle">Пазлы</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/creation">Творчество</a></li>
            <li><a href="/printedproducts">Печатная продукция</a></li>
            <li><a href="/plaything">Игрушки</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<table class="table table-bordered">

  <tbody>
  <% @toys.each do |toy| %>
    <tr style="display: block; Margin-bottom:30px">
      <td style="width: 200px;"><%= toy.name %> &nbsp</td>
      <td><%= toy.cost %> руб. &nbsp</td>
      <td><%= image_tag(toy.image, size: "100x100", alt: toy.image[1..-5]) %> &nbsp</td>
      <td><%= link_to 'Полная информация', toy, class: "btn btn-default" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Toy', new_toy_path %>

app/views/toys/lacing.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand и toggle сгруппированы для лучшего отображения на мобильных дисплеях -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="/razrbs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-top: 15px"><%= image_tag("/brand.jpeg") %></a>
    </div>
    <div class="container-fluid">
      <%= image_tag("/nadpis.jpeg", class: "navbar-text") %>
      <a href="/contakt" class="navbar-text" style="margin-top: 60px">Наши контакты</a>
      <%#= image_tag("/kalash1.jpg", size: "150x75")%>
    </div>
    <div class="container-fluid">
      <%= image_tag("/kalash1.jpg", size: "170x100") %>
      <%= image_tag("/kalash3.jpg", size: "170x100") %>
      <%= image_tag("/kalash4.jpg", size: "170x100") %>
      <%= image_tag("/kalash5.jpg", size: "170x100") %>
      <%= image_tag("/kalash2.jpg", size: "170x100")%>
    </div>
    <!-- Соберите навигационные ссылки, формы, и другой контент для переключения -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="/razr">Каталог <span class="sr-only">(current)</span></a></li>-->
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Деревянные игрушки <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/shumelki">Шумелки</a></li>
            <li><a href="/pyramid">Пирамидки</a></li>
            <li><a href="/lacing">Шнуровки</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/puzzlespictures">Пазлы-картинки</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/looseleaves">Вкладыши</a></li>
            <li><a href="/sorters">Сортеры</a></li>
            <li><a href="/cubes">Кубики</a></li>
            <li><a href="/boardgames">Настольные игры</a></li>
            <li><a href="/constructors">Конструкторы</a></li>
            <li><a href="/creatorskit">Наборы для творчества</a></li>
            <li><a href="/puzzles">Пазлы</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Обучающие игры <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/learningtoread">Обучение чтению</a></li>
            <li><a href="/westudythealphabet">Изучаем алфавит</a></li>
            <li><a href="/languageandcommunication">Язык и коммуникация</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/accounteducation">Обучение счету</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/developmentoflogicalthinking">Развитие логического мышления</a></li>
            <li><a href="/developmentofmemoryandattention">Развитие памяти и внимания</a></li>
            <li><a href="/colorsandshapes">Цвета и формы</a></li>
            <li><a href="/theworld">Окружающий мир</a></li>
          </ul>
        </li>
        <li><a href="/puzzlegames">Головоломки</a></li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Настольные игры <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/teaching">Обучающие</a></li>
            <li><a href="/developing">Развивающие</a></li>
            <li><a href="/merry">Веселые</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/forthecompany">Для компании</a></li>
          </ul>
        </li>
        <li><a href="/constructor">Конструкторы</a></li>
        <li class="dropdown">
          <a href="/razr" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Остальное <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/massformodeling">Масса для лепки</a></li>
            <li><a href="/sandformodeling">Песок для лепки</a></li>
            <li><a href="/puzzle">Пазлы</a></li>
            <!--<li role="separator" class="divider"></li>-->
            <li><a href="/creation">Творчество</a></li>
            <li><a href="/printedproducts">Печатная продукция</a></li>
            <li><a href="/plaything">Игрушки</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<table class="table table-bordered">

  <tbody>
  <% @toys.each do |toy| %>
    <tr style="display: block; Margin-bottom:30px">
      <td style="width: 200px;"><%= toy.name %> &nbsp</td>
      <td><%= toy.cost %> руб. &nbsp</td>
      <td><%= image_tag(toy.image, size: "100x100", alt: toy.image[1..-5]) %> &nbsp</td>
      <td><%= link_to 'Полная информация', toy, class: "btn btn-default" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Toy', new_toy_path %>